# Generated by Django 5.2.8 on 2025-12-01 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('car_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vin', models.TextField(db_column='VIN')),
                ('plate_number', models.IntegerField(blank=True, null=True)),
                ('name_car', models.TextField()),
                ('make', models.TextField()),
                ('model', models.TextField()),
                ('year', models.IntegerField()),
                ('color', models.TextField()),
                ('engine_size', models.TextField()),
                ('fuel_type', models.TextField()),
                ('engine_capecity', models.IntegerField()),
                ('gear_type', models.IntegerField()),
                ('receipt_number', models.IntegerField(blank=True, null=True)),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('mileage', models.IntegerField()),
            ],
            options={
                'db_table': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('report_id', models.IntegerField(primary_key=True, serialize=False)),
                ('import_type', models.TextField()),
                ('import_file', models.TextField()),
                ('rating', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('password_hash', models.TextField()),
                ('email', models.TextField()),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Accidents',
            fields=[
                ('accident_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_accident', models.TextField(blank=True, null=True)),
                ('damaged_parts', models.TextField()),
                ('accident_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.cars')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.reports')),
            ],
            options={
                'db_table': 'Accidents',
            },
        ),
        migrations.CreateModel(
            name='ImageAccident',
            fields=[
                ('img_acc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('img_accident', models.BinaryField(blank=True, null=True)),
                ('uploaded_at', models.DateField(blank=True, null=True)),
                ('accident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.accidents')),
            ],
            options={
                'db_table': 'image_accident',
            },
        ),
        migrations.CreateModel(
            name='ImageCar',
            fields=[
                ('img_car_id', models.IntegerField(primary_key=True, serialize=False)),
                ('img_car', models.BinaryField(blank=True, null=True)),
                ('uploaded_at', models.DateField(blank=True, null=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.cars')),
            ],
            options={
                'db_table': 'image_car',
            },
        ),
        migrations.AddField(
            model_name='cars',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.reports'),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('evaluation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.cars')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.users')),
            ],
            options={
                'db_table': 'evaluation',
            },
        ),
        migrations.CreateModel(
            name='WorkshopsData',
            fields=[
                ('workshop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mech_insp_desc', models.TextField(blank=True, null=True)),
                ('comp_scan_desc', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.cars')),
            ],
            options={
                'db_table': 'Workshops_data',
            },
        ),
    ]
